### model
model_name_or_path: /inspire/hdd/ws-8207e9e2-e733-4eec-a475-cfa1c36480ba/embodied-multimodality/liuxiaoran-240108120089/train/models/Llama-3.2-3B-fla-hybrid-sort2-local
trust_remote_code: true

### method
stage: pt
do_train: true
finetuning_type: full
# lora_rank: 8
# lora_target: all
deepspeed: examples/deepspeed/ds_z3_config.json
flash_attn: fa2

### dataset
dataset: LongWanjuan
cutoff_len: 32768
# max_samples: 100000
overwrite_cache: true
# preprocessing_num_workers: 16
preprocessing_num_workers: 64
# dataloader_num_workers: 4
dataloader_num_workers: 16

### output
output_dir: /inspire/hdd/ws-8207e9e2-e733-4eec-a475-cfa1c36480ba/embodied-multimodality/liuxiaoran-240108120089/train/saves/llama3.2-3B-fla-sort2-local
logging_steps: 10
save_steps: 400
plot_loss: true
overwrite_output_dir: true
save_only_model: false

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
# learning_rate: 1.0e-4
learning_rate: 3.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# eval_dataset: c4_demo
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
